// <auto-generated />
using CrmLeadManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;


#nullable disable

namespace CrmLeadManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrmLeadManagement.Models.FollowUpSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutoEscalateAfterDaysOverdue")
                        .HasColumnType("int");

                    b.Property<string>("DefaultFollowUpType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefaultReminderDaysBefore")
                        .HasColumnType("int");

                    b.Property<bool>("EnableEmailReminders")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableSmsReminders")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FollowUpSettings");
                });
                

            modelBuilder.Entity("CrmLeadManagement.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FollowUpDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LeadName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId")
                        .IsUnique();

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("CrmLeadManagement.Models.LeadSourceOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("SourceOptions");
                });

            modelBuilder.Entity("CrmLeadManagement.Models.LeadStatusOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("StatusOptions");
                });

            modelBuilder.Entity("CrmLeadManagement.Models.UserRoleEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CrmLeadManagement.Models.Lead", b =>
                {
                    b.OwnsMany("CrmLeadManagement.Models.AssignmentEntry", "AssignmentHistory", b1 =>
                        {
                            b1.Property<int>("LeadId_FK")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AssignedEmployee")
                                .IsRequired()
                                .HasColumnType("varchar(max)");

                            b1.Property<string>("AssignmentDate")
                                .IsRequired()
                                .HasColumnType("varchar(max)");

                            b1.Property<string>("Remarks")
                                .IsRequired()
                                .HasColumnType("varchar(max)");

                            b1.HasKey("LeadId_FK", "Id");

                            b1.ToTable("AssignmentEntry");

                            b1.WithOwner()
                                .HasForeignKey("LeadId_FK");
                        });

                    b.OwnsMany("CrmLeadManagement.Models.CallHistoryEntry", "CallHistory", b1 =>
                        {
                            b1.Property<int>("LeadId_FK")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("CallDate")
                                .IsRequired()
                                .HasColumnType("varchar(max)");

                            b1.Property<string>("CallStatus")
                                .IsRequired()
                                .HasColumnType("varchar(max)");

                            b1.Property<string>("CallTime")
                                .IsRequired()
                                .HasColumnType("varchar(max)");

                            b1.Property<string>("CallType")
                                .IsRequired()
                                .HasColumnType("varchar(max)");

                            b1.Property<string>("Duration")
                                .IsRequired()
                                .HasColumnType("varchar(max)");

                            b1.Property<string>("Employee")
                                .IsRequired()
                                .HasColumnType("varchar(max)");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasColumnType("varchar(max)");

                            b1.HasKey("LeadId_FK", "Id");

                            b1.ToTable("CallHistoryEntry");

                            b1.WithOwner()
                                .HasForeignKey("LeadId_FK");
                        });

                    b.OwnsMany("CrmLeadManagement.Models.EstimationEntry", "Estimations", b1 =>
                        {
                            b1.Property<int>("LeadId_FK")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("AttachmentFileName")
                                .IsRequired()
                                .HasColumnType("varchar(max)");

                            b1.Property<string>("AttachmentPath")
                                .IsRequired()
                                .HasColumnType("varchar(max)");

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasColumnType("varchar(max)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("varchar(max)");

                            b1.Property<string>("Discount")
                                .IsRequired()
                                .HasColumnType("varchar(max)");

                            b1.Property<string>("LeadCustomer")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ProjectRequirement")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Rate")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Subtotal")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Tax")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TermsConditions")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Total")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ValidUntil")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("LeadId_FK", "Id");

                            b1.ToTable("Estimations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LeadId_FK");

                            b1.OwnsMany("CrmLeadManagement.Models.FinanceLineItem", "Items", b2 =>
                                {
                                    b2.Property<int>("EstimationId_FK")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Amount")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ItemName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Quantity")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Rate")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("EstimationId_FK", "Id");

                                    b2.ToTable("EstimationLineItems", (string)null);

                                    b2.WithOwner("Estimation")
                                        .HasForeignKey("EstimationId_FK")
                                        .HasPrincipalKey("Id");

                                    b2.Navigation("Estimation");
                                });

                            b1.Navigation("Items");
                        });

                    b.OwnsMany("CrmLeadManagement.Models.FollowUpEntry", "FollowUps", b1 =>
                        {
                            b1.Property<int>("LeadId_FK")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AssignedEmployee")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FollowUpDate")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FollowUpTime")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FollowUpType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Remarks")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("LeadId_FK", "Id");

                            b1.ToTable("FollowUpEntry");

                            b1.WithOwner()
                                .HasForeignKey("LeadId_FK");
                        });

                    b.OwnsMany("CrmLeadManagement.Models.ProposalEntry", "Proposals", b1 =>
                        {
                            b1.Property<int>("LeadId_FK")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AttachmentFileName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("AttachmentPath")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Budget")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Deliverables")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LeadCustomer")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ProjectRequirement")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ScopeOfWork")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TermsConditions")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Timeline")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("LeadId_FK", "Id");

                            b1.ToTable("Proposals", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LeadId_FK");
                        });

                    b.OwnsMany("CrmLeadManagement.Models.QuotationEntry", "Quotations", b1 =>
                        {
                            b1.Property<int>("LeadId_FK")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AttachmentFileName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("AttachmentPath")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Discount")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("GrandTotal")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LeadCustomer")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ProjectRequirement")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Subtotal")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Tax")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TermsConditions")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ValidUntil")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("LeadId_FK", "Id");

                            b1.ToTable("Quotations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LeadId_FK");

                            b1.OwnsMany("CrmLeadManagement.Models.FinanceLineItem", "Items", b2 =>
                                {
                                    b2.Property<int>("QuotationId_FK")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Amount")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ItemName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Quantity")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Rate")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("QuotationId_FK", "Id");

                                    b2.ToTable("QuotationLineItems", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("QuotationId_FK")
                                        .HasPrincipalKey("Id");
                                });

                            b1.Navigation("Items");
                        });

                    b.OwnsMany("CrmLeadManagement.Models.RequirementEntry", "Requirements", b1 =>
                        {
                            b1.Property<int>("LeadId_FK")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Budget")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Details")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ExpectedDate")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ImagePath")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ItemName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Priority")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Quantity")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Remarks")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("RequirementType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("LeadId_FK", "Id");

                            b1.ToTable("RequirementEntry");

                            b1.WithOwner()
                                .HasForeignKey("LeadId_FK");
                        });

                    b.OwnsMany("CrmLeadManagement.Models.VisitEntry", "Visits", b1 =>
                        {
                            b1.Property<int>("LeadId_FK")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Conversation")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Employee")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Outcome")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Remarks")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("VisitDate")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("VisitLocation")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("VisitTime")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("LeadId_FK", "Id");

                            b1.ToTable("VisitEntry");

                            b1.WithOwner()
                                .HasForeignKey("LeadId_FK");
                        });

                    b.Navigation("AssignmentHistory");

                    b.Navigation("CallHistory");

                    b.Navigation("Estimations");

                    b.Navigation("FollowUps");

                    b.Navigation("Proposals");

                    b.Navigation("Quotations");

                    b.Navigation("Requirements");

                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
